"""empty message

Revision ID: 258b00a20e0b
Revises: 94f811650c2b
Create Date: 2025-04-09 21:22:11.237563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258b00a20e0b'
down_revision = '94f811650c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_char',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_char')
    # ### end Alembic commands ###
