"""empty message

Revision ID: 94f811650c2b
Revises: 7beed97304ac
Create Date: 2025-04-07 23:13:24.512748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f811650c2b'
down_revision = '7beed97304ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hair_color', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('height', sa.String(length=20), nullable=False))
        batch_op.drop_column('is_active')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weather', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('size')
        batch_op.drop_column('age')
        batch_op.drop_column('weather')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('height')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('hair_color')

    # ### end Alembic commands ###
